### ISSUE TITLE
[BUG] I cannot start application after installing.

### ISSUE THREAD

**Issue by Kiliwwwww** [CodeCraftersCN/jdevkit#8] opened 2023-08-28 05:58 UTC
**Which module creates this bug**
- [ ] `devkit-core`
- [ ] `devkit-utils`
- [x] `guid`
- [ ] `webcal`
- [x] `simple-jwt-facade`
- [x] `simple-jwt-authzero`
- [ ] `simple-jwt-jjwt`
- [x] `simple-jwt-spring-boot-starter`

**Describe the bug**

I properly installed and configured the `simple-jwt` module properly but the application cannot be started.

**To Reproduce**

1. Install this module onto a Spring Boot Application by adding these codes to `build.gradle`

   ```groovy
   dependencies {
     // other dependencies
     // Simple JWT
     implementation 'cn.org.codecrafters:simple-jwt-authzero:1.0.0'
     implementation 'cn.org.codecrafters:simple-jwt-spring-boot-starter:1.0.0'
   }
   ```

2. Configure this module in application configuration file in yaml format.

   ```yaml
   code-crafters:
     simple-jwt:
       algorithm: hs256
       secret: a_sample_secret
       issuer: a_sample_issuer
   ```
3. Additional configuration which used this module.

   I also added several `SnowflakeGuidCreator` to help create ids for entities in this project. Configured as follows:

   ```java
   @Configuration
   public class GuidConfig {
   
       /**
        * This guid creator is designed for create id for admins.
        */
       @Bean
       public SnowflakeGuidCreator adminGuidUtil() {
           return new SnowflakeGuidCreator(0x0, 0x0);
       }
   
       /**
        * This guid creator is designed for create id for users.
        */
       @Bean
       public SnowflakeGuidCreator userGuidUtil() {
           return new SnowflakeGuidCreator(0x0, 0x1);
       }
   
       /**
        * This guid creator is designed for create id for admins' logs.
        */
       @Bean
       public SnowflakeGuidCreator adminLogGuidUtil() {
           return new SnowflakeGuidCreator(0x1, 0x0);
       }
   
       /**
        * This guid creator is designed for create id for users' logs.
        */
       @Bean
       public SnowflakeGuidCreator userLogGuidUtil() {
           return new SnowflakeGuidCreator(0x1, 0x1);
       }
   
       /**
        * This guid creator is designed for create id for dictation tests.
        */
       @Bean
       public SnowflakeGuidCreator dictationGuidUtil() {
           return new SnowflakeGuidCreator(0x2, 0x0);
       }
   
       /**
        * This guid creator is designed for create id for dictation details.
        */
       @Bean
       public SnowflakeGuidCreator dictationDetailGuidUtil() {
           return new SnowflakeGuidCreator(0x2, 0x1);
       }
   
       /**
        * This guid creator is designed for create id for tags.
        */
       @Bean
       public SnowflakeGuidCreator tagGuidUtil() {
           return new SnowflakeGuidCreator(0x3, 0x0);
       }
   
       /**
        * This guid creator is designed for create id for words.
        */
       @Bean
       public SnowflakeGuidCreator wordGuidUtil() {
           return new SnowflakeGuidCreator(0x4, 0x0);
       }
   
       /**
        * This guid creator is designed for create id for word descriptions.
        */
       @Bean
       public SnowflakeGuidCreator wordDescriptionsGuidUtil() {
           return new SnowflakeGuidCreator(0x4, 0x1);
       }
   
       /**
        * This guid creator is designed for create id for binding a word and tags.
        */
       @Bean
       public SnowflakeGuidCreator wordTagsGuidUtil() {
           return new SnowflakeGuidCreator(0x4, 0x2);
       }
   
   }
   ```
4. When I run this application, I got the following error:

   ```text
   Parameter 0 of constructor in UserInterceptor required a bean of type 'cn.org.codecrafters.simplejwt.TokenResolver' that could not be found.
   ```

   The most helpful related error reports:

   ```text
   Positive matches:
   -----------------
   
      GuidAutoConfiguration matched:
         - @ConditionalOnMissingBean (names: jtiCreator; SearchStrategy: all) did not find any beans (OnBeanCondition)
         
   Negative matches:
   -----------------
   
      AuthzeroTokenResolverAutoConfiguration#tokenResolver:
         Did not match:
            - @ConditionalOnBean (names: jtiCreator types: cn.org.codecrafters.guid.GuidCreator; SearchStrategy: all) did not find any beans named jtiCreator (OnBeanCondition)
   
   ```

**Expected behavior**
The module is properly installed and create, resolve JWTs in this application.

**Screenshots**

No screenshots could be applied.

**Developing Environment:**
 - OS: macOS
 - Browser: safari
 - Version: 1.0.0
 - Java Version: Amazon Corretto 17.0.7

**Additional context**
Nothing.

**Comment by zihluwang** [comment] 2023-08-28 06:37
This problem is caused by the incorrect order when initialising bean `jtiCreator` and `authzeroTokenResolver`. This problem is fixed by adjusting the order of initialisation of these two beans. And the order of initialising bean `jjwtTokenResolver` has also been adjusted.

Please upgrade to v1.0.1 to fix this issue or add a `jtiCreator` bean by the following codes:
```java
@org.springframework.context.annotation.Configuration
public class JtiConfiguration /* or any other name you like*/ {
    @Bean
    public GuidCreator<?> jtiCreator() {
        return UUID::randomUUID; //  or any implementation you like
    }
}
```

**Closed by zihluwang** 2023-08-28 06:37 UTC
Labels: bug
